### ISSUE TITLE
LaTeX Formulas in Markdown Files aren't supported

### ISSUE THREAD

**Issue by az15240** [yaoyao-liu/minimal-light#16]
I found your template very helpful and I built my website upon it. I want to add some LaTeX formulas to my markdown file, but it doesn't work. Check out [example](https://az15240.github.io/blog/blog_entry1.html) and [example](https://az15240.github.io/blog/blog_entry2.html). 

I tried to run those pandoc commands in Makefile standalone locally, and the LaTeX formulas are rendering properly. 

I tried using both the original Makefile, and added `--mathjax` in `PANDOC_OPTIONS`, but both ways didn't succeed.

**Comment by yaoyao-liu** [comment]
Thanks for your interest in my project!

This project is built on Jekyll. In the default setting, it doesn't support MathJax. If you hope to use MathJax, you may follow this tutorial:
https://webdocs.cs.ualberta.ca/~zichen2/blog/coding/setup/2019/02/17/how-to-add-mathjax-support-to-jekyll.html

If you have any further questions, please feel free to let me know.

Best,

Yaoyao

**Comment by az15240** [comment]
Thank you for the tutorial. I followed that tutorial and I also looked up a few. When I typed `$f(x)$` it renders to `\(f(x)\)` and `$$f(x)$$` to `\[f(x)\]`. Seems like it is doing some conversion but I have no idea why it is not displaying the math equations normally. Do you know why? 

Regards,
Stanley

**Comment by yaoyao-liu** [comment]
I tried the tutorial I sent you. It works well on my theme. I uploaded the new code with MathJax here in case you need it:
https://drive.google.com/file/d/1WzkgPd13fC6d5SicHmM1t8tseQqKIv55/view?usp=sharing

If you have any further questions, please feel free to contact me.

Best,

Yaoyao

**Comment by az15240** [comment]
Thank you so much, it worked! Seems like I added the HTML code to the wrong place. 

For whoever read this issue in the future, the HTML code in the tutorial should be added to `_layouts/homepage.html`, instead of `_includes/head.html`. 

Regards,
Stanley
