### ISSUE TITLE
how to adjust the size of avatar

### ISSUE THREAD

**Issue by tao-bai** [yaoyao-liu/minimal-light#2]
It is a little small and want to make it bigger. Could you please help?

**Comment by yaoyao-liu** [comment]
Hi,

You may adjust the CSS file to change the layout of this page. For the avatar, you can adjust the parameters in this line:
https://github.com/yaoyao-liu/minimal-light/blob/4883931596f3bb5aa4061bc9b64a318b83be9f16/_sass/minimal-light.scss#L92

**Comment by tao-bai** [comment]
Thanks for your reply!
But it doesn't work. I changed the width to 100% and no difference.

**Comment by tao-bai** [comment]
thanks! everything looks fine!
