### ISSUE TITLE
how to add pictures for publications in index.md file?

### ISSUE THREAD

**Issue by ssssholmes** [yaoyao-liu/minimal-light#4]

**Comment by ssssholmes** [comment]
<img width="671" alt="截屏2022-02-12 16 18 14" src="https://user-images.githubusercontent.com/48430696/153703384-37ff8e38-1e5c-4e5e-8194-dde11a197990.png">

**Comment by ssssholmes** [comment]
Could you give me some hints about how to add a picture for a paper in md file? Thanks!

**Comment by yaoyao-liu** [comment]
Hi @ssssholmes,

Thanks for your interest in my project.
You may see the source code of my website here: <https://github.com/yaoyao-liu/my-homepage>
I haven't cleaned that project. So it might be a little difficult to find the corresponding part. I am sorry about that.

If you have any further questions, feel free to message me.

Best,
Yaoyao

**Comment by ssssholmes** [comment]
@yaoyao-liu Thank you again for your help. I would have a try.
