### ISSUE TITLE
[Feature Request] Add more icons to the sidebar and align them left

### ISSUE THREAD

**Issue by yzhangcs** [yaoyao-liu/minimal-light#5]
@yaoyao-liu Hi, thank you for maintaining this great theme.
I've successfully built my own personal [academic website](https://yzhang.site) using your template. It looks very clean and elegant!
But from the perspective of a academic homepage, I need more links to present myself, similar to [academicpages](https://academicpages.github.io/).
You have provided some examples in _config.yml but only for google scholar/github/linkedin.
I also found that more than three icons horizontally side by side looks very crowded.

**Alternative**: It would be nice to provide interfaces for adding more icons vertically side-by-side to the sidebar. 
The final presentation could be the following example I picked from [academicpages](https://academicpages.github.io/)
![image](https://user-images.githubusercontent.com/18402347/196054718-a827a450-1398-4c9a-9d39-b4cb3df3370c.png).
I've tried myself to modify the layout files. But I'm not an expert in html/css, so unsurprisingly it failed.

Thank you very much for taking a look at this!

**Comment by yaoyao-liu** [comment]
@yzhangcs 

I have updated the layout of the sidebar. If you have any further suggestions, please feel free to let me know.
