### ISSUE TITLE
How to set light theme permanently?

### ISSUE THREAD

**Issue by harishankarv** [yaoyao-liu/minimal-light#6]
Hi, 

Fantastic theme Yaoyao. 

I had a quick question. Is there a way to permanently set to the light theme? On my phone and laptop, I believe it chooses the theme based on the system theme. I tried modifying the `minimal-light.scss` file, but did not have satisfying results. Is there one global setting to do this?

**Comment by harishankarv** [comment]
I realized this can be done by commenting out the  `@media (prefers-color-scheme: dark)`  blocks in `_sass/minimal-light.scss` and also in `assets/css/publications.css`

**Comment by yaoyao-liu** [comment]
Hello @harishankarv 

Thanks for your suggestion. Now I added a parameter that allows the users to disable the dark theme:
https://github.com/yaoyao-liu/minimal-light/blob/363a871b453bb28189489a791163dd146b7d8c65/_config.yml#L31-L33
